# default LSST Atmosphere File (alpha)

atmosphereTableFile: fgcm_atm_lsst2.fits

elevation: 2663.0

pmbRange: [770.0,790.0]
pmbSteps: 5

pwvRange: [0.1,12.0]
pwvSteps: 21

o3Range: [220.0,310.0]
o3Steps: 3

tauRange: [0.002,0.35]
tauSteps: 11

alphaRange: [0.0,2.0]
alphaSteps: 9

zenithRange: [0.0,70.0]
zenithSteps: 21

pmbStd: 778.0
pwvStd: 3.0
o3Std: 263.0
tauStd: 0.030
alphaStd: 1.0
airmassStd: 1.2
